version: '3'

services:
  neo4j:
    image: neo4j:latest
    volumes:
      - neo4j-data:/data
      - ./import:/var/lib/neo4j/import
    ports:
      - "127.0.0.1:7474:7474"
      - "127.0.0.1:7687:7687"
    environment:
      NEO4J_AUTH: none

volumes:
  neo4j-data:
